[package]
name = "nu_plugin_start"
version = "0.1.0"
authors = ["Elton <eltonp3103@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-plugin = { path = "../nu-plugin", version = "0.13.0" }
nu-protocol = { path = "../nu-protocol", version = "0.13.0" }
nu-source = { path = "../nu-source", version = "0.13.0" }
nu-errors = { path = "../nu-errors", version = "0.13.0" }
url = "2.1.1"
# open = "1.4.0"

[build-dependencies]
nu-build = { version = "0.13.0", path = "../nu-build" }
